### ISSUE TITLE
strictNullChecks が有効になっていない？

### ISSUE THREAD

**Issue by waki285** [tekihei2317/type-challenges-judge#14]
![image](https://user-images.githubusercontent.com/67305123/175872402-6b566009-08aa-4ca7-98e5-26c8de5ee057.png)
![image](https://user-images.githubusercontent.com/67305123/175872426-6208068d-aaa2-493c-94f9-6a3ec49b181a.png)
ここはstrictNullChecksがtrueであればAcceptedな気がします。

**Comment by tekihei2317** [comment]
ご指摘ありがとうございます！
修正しましたので、再度提出していただければAcceptedになるはずです😃

**Comment by waki285** [comment]
なりました！:smile:
